#!/bin/bash
cat ./lf_core.js
cat ./jsBindings/offsets.js
cat ./jsBindings/Common/b2Math.js
cat ./jsBindings/Collision/b2Collision.js
cat ./jsBindings/Collision/Shapes/b2EdgeShape.js
cat ./jsBindings/Collision/Shapes/b2PolygonShape.js
cat ./jsBindings/Collision/Shapes/b2Shape.js
cat ./jsBindings/Collision/Shapes/b2ChainShape.js
cat ./jsBindings/Collision/Shapes/b2CircleShape.js
cat ./jsBindings/Dynamics/b2Body.js
cat ./jsBindings/Dynamics/b2World.js
cat ./jsBindings/Dynamics/Joints/b2WheelJoint.js
cat ./jsBindings/Dynamics/Joints/b2WeldJoint.js
cat ./jsBindings/Dynamics/Joints/b2GearJoint.js
cat ./jsBindings/Dynamics/Joints/b2Joint.js
cat ./jsBindings/Dynamics/Joints/b2FrictionJoint.js
cat ./jsBindings/Dynamics/Joints/b2RevoluteJoint.js
cat ./jsBindings/Dynamics/Joints/b2MotorJoint.js
cat ./jsBindings/Dynamics/Joints/b2PulleyJoint.js
cat ./jsBindings/Dynamics/Joints/b2DistanceJoint.js
cat ./jsBindings/Dynamics/Joints/b2PrismaticJoint.js
cat ./jsBindings/Dynamics/Joints/b2RopeJoint.js
cat ./jsBindings/Dynamics/Joints/b2MouseJoint.js
cat ./jsBindings/Dynamics/Contacts/b2Contact.js
cat ./jsBindings/Dynamics/b2Fixture.js
cat ./jsBindings/Dynamics/b2WorldCallbacks.js
cat ./jsBindings/Particle/b2ParticleSystem.js
cat ./jsBindings/Particle/b2ParticleGroup.js
cat ./jsBindings/Particle/b2Particle.js
